policy:
  - section:
      - id: [project]
        block-list: ['None', 'Other']
        label:
          - name: 'project/userscript/ccna'
            keys: ['Userscript/CCNA']
          - name: 'project/userscript/armyforge'
            keys: ['Userscript/Armyforge']
