name: Bug
description: Create an issue for a bug or error in the project.
labels: bug
assignees: ''

body:
  - type: dropdown
    id: project
    attributes:
      label: 'Choose the project'
      options:
        - 'project/userscript/ccna'
        - 'project/minecraft-mod'
    required: true

  - type: input
    id: version
    attributes:
      label: 'Version of the project'
      placeholder: 'Enter version'
    required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 'Description of the bug and steps to reproduce'
      placeholder: 'Describe the steps to reproduce the bug'
    required: true

  - type: file
    id: screenshot
    attributes:
      label: 'Optional Screenshot'
      description: 'Upload a screenshot that helps describe the issue'
    required: false
