name: Bug
description: Create an issue for a bug or error in the project.
labels: bug

body:
  - type: dropdown
    id: project
    attributes:
      label: 'Choose the project'
      options:
        - 'Userscript/CCNA'
        - 'Userscript/Armyforge'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 'Version of the project'
      placeholder: 'Enter version'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 'Description of the bug'
      placeholder: 'Describe the Bug'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 'Description how to reproduce the bug'
      placeholder: |
        - [ ] step 1
        - [ ] step 2
        - [ ] step 3
        - [ ] X goes wrong
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 'Optional Screenshots'
      description: 'Upload a screenshot that helps describe the issue'
    validations:
      required: false
