name: Bug
description: Create an issue for a bug or error in the project.
labels: bug

body:
  - type: dropdown
    id: project
    attributes:
      label: 'Choose the project'
      options:
        - 'project/userscript/ccna'
        - 'project/minecraft-mod'
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: 'Version of the project'
      placeholder: 'Enter version'
    validations:
      required: false

  - type: textarea
    id: reproduction
    attributes:
      label: 'Description of the bug and steps to reproduce'
      placeholder: 'Describe the steps to reproduce the bug'
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: 'Optional Screenshots'
      description: 'Upload a screenshot that helps describe the issue'
    validations:
      required: false
